Repository Ebrisoft/Frontend, pull requests merged in 2019-12, with the labels that each got.

#25 Hotfix/routining bug for new issue#2
  src/app/views/tenant/issue-feed/issue-feed.page.ts
  src/app/views/tenant/tabs/tabs.router.module.ts
Labels: enhancement

#26 Feature/add new issue landlord#3
  src/app/models/request/landlord/create-issues-request.interface.ts
  src/app/services/api/landlord/create-issue-api-service.ts
  src/app/utils/priority.enum.ts
  src/app/views/landlord/issue-feed/issue-feed.page.html
  src/app/views/landlord/issue-feed/issue-feed.page.ts
  src/app/views/landlord/new-issue/new-issue.module.ts
  src/app/views/landlord/new-issue/new-issue.page.html
  src/app/views/landlord/new-issue/new-issue.page.scss
  src/app/views/landlord/new-issue/new-issue.page.spec.ts
  src/app/views/landlord/new-issue/new-issue.page.ts
  src/app/views/landlord/tabs/tabs.router.module.ts
  tslint.json
Labels: enhancement

#31 Feature/style add issue page#28
  src/app/views/landlord/new-issue/new-issue.page.html
  src/app/views/landlord/new-issue/new-issue.page.scss
  src/app/views/landlord/new-issue/new-issue.page.ts
  src/app/views/tenant/new-issue/new-issue.page.html
  src/app/views/tenant/new-issue/new-issue.page.scss
  src/app/views/tenant/new-issue/new-issue.page.ts
Labels: enhancement

#29 Added ion-refresher that makes getIssue request when pulled down
  src/app/views/landlord/issue-feed/issue-feed.page.html
  src/app/views/landlord/issue-feed/issue-feed.page.ts
  src/app/views/tenant/issue-feed/issue-feed.page.html
  src/app/views/tenant/issue-feed/issue-feed.page.ts
Labels: enhancement

#35 Implemented the Angular httpClient into the Cordova http service
  package.json
  src/app/app.module.ts
  src/app/services/http/http-cordova.ts
Labels: bug, enhancement

#34 Updated application stylesheet, issue styling, added priority to land…
  src/app/components/landlord/issue-card/issue-card.component.html
  src/app/components/landlord/issue-card/issue-card.component.scss
  src/app/components/landlord/issue-card/issue-card.component.ts
  src/app/components/tenant/issue-card/issue-card.component.html
  src/app/components/tenant/issue-card/issue-card.component.scss
  src/app/components/tenant/issue-card/issue-card.component.ts
  src/app/models/response/landlord/issue-response.interface.ts
  src/app/views/landlord/issue-feed/issue-feed.page.html
  src/app/views/tenant/issue-feed/issue-feed.page.html
  src/theme/variables.scss
Labels: enhancement

#37 Feature/landlord change house context#30
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/landlord/house-list-item/house-list-item.component.html
  src/app/components/landlord/house-list-item/house-list-item.component.scss
  src/app/components/landlord/house-list-item/house-list-item.component.spec.ts
  src/app/components/landlord/house-list-item/house-list-item.component.ts
  src/app/components/landlord/page-header/page-header.component.html
  src/app/components/landlord/page-header/page-header.component.scss
  src/app/components/landlord/page-header/page-header.component.spec.ts
  src/app/components/landlord/page-header/page-header.component.ts
  src/app/components/landlord/page-header/page-header.module.ts
  src/app/components/tenant/page-header/page-header.component.html
  src/app/components/tenant/page-header/page-header.component.scss
  src/app/components/tenant/page-header/page-header.component.spec.ts
  src/app/components/tenant/page-header/page-header.component.ts
  src/app/components/tenant/page-header/page-header.module.ts
  src/app/models/response/landlord/house-response.interface.ts
  src/app/services/api/landlord/houses-api.service.ts
  src/app/services/observables/current-house-service.ts
  src/app/services/pipes/filter-issues.pipe.ts
  src/app/views/landlord/house-select/house-select.module.ts
  src/app/views/landlord/house-select/house-select.page.html
  src/app/views/landlord/house-select/house-select.page.scss
  src/app/views/landlord/house-select/house-select.page.spec.ts
  src/app/views/landlord/house-select/house-select.page.ts
  src/app/views/landlord/issue-feed/issue-feed.module.ts
  src/app/views/landlord/issue-feed/issue-feed.page.html
  src/app/views/landlord/issue-feed/issue-feed.page.ts
  src/app/views/landlord/new-issue/new-issue.page.html
  src/app/views/landlord/new-issue/new-issue.page.ts
  src/app/views/landlord/tabs/tabs.router.module.ts
  src/app/views/tenant/issue-feed/issue-feed.module.ts
  src/app/views/tenant/issue-feed/issue-feed.page.html
  src/app/views/tenant/new-issue/new-issue.page.html
  src/app/views/tenant/new-issue/new-issue.page.ts
  src/app/views/tenant/pinboard/pinboard.module.ts
  src/app/views/tenant/pinboard/pinboard.page.html
Labels: enhancement

#41 Fixed color scheme for new app header.
  src/app/components/landlord/page-header/page-header.component.html
  src/app/components/landlord/page-header/page-header.component.ts
  src/app/components/tenant/page-header/page-header.component.html
  src/app/views/landlord/new-issue/new-issue.page.html
  src/app/views/tenant/new-issue/new-issue.page.html
Labels: bug

#46 Styled login page
  src/app/views/login/login.page.html
  src/app/views/login/login.page.scss
  src/app/views/login/login.page.ts
  src/assets/habitat-login-bg.png
Labels: enhancement

#48 Feature/style issue detail view#47
  src/app/components/landlord/issue-card/issue-card.component.ts
  src/app/services/api/landlord/issue-api-service.ts
  src/app/views/landlord/issue-detail/issue-detail.page.html
  src/app/views/landlord/issue-detail/issue-detail.page.scss
  src/app/views/landlord/issue-detail/issue-detail.page.ts
  src/app/views/tenant/issue-detail/issue-detail.page.html
  src/app/views/tenant/issue-detail/issue-detail.page.scss
  src/app/views/tenant/issue-detail/issue-detail.page.ts
Labels: enhancement

#54 Feature/style remaining views phonebook and house select#53
  src/app/components/landlord/house-list-item/house-list-item.component.html
  src/app/components/landlord/house-list-item/house-list-item.component.ts
  src/app/components/landlord/phonebook-item/phonebook-item.component.html
  src/app/components/landlord/phonebook-item/phonebook-item.component.scss
  src/app/components/landlord/phonebook-item/phonebook-item.component.ts
  src/app/components/tenant/phonebook-item/phonebook-item.component.html
  src/app/components/tenant/phonebook-item/phonebook-item.component.scss
  src/app/components/tenant/phonebook-item/phonebook-item.component.ts
  src/app/views/landlord/house-select/house-select.page.html
  src/app/views/landlord/house-select/house-select.page.scss
  src/app/views/landlord/house-select/house-select.page.ts
  src/app/views/landlord/new-issue/new-issue.module.ts
  src/app/views/landlord/new-issue/new-issue.page.html
  src/app/views/landlord/new-issue/new-issue.page.ts
  src/app/views/landlord/phonebook/phonebook.page.html
  src/app/views/landlord/tabs/tabs.page.html
  src/app/views/tenant/tabs/tabs.page.html
Labels: enhancement

#55 Issue view now refreshes when issue view state is altered
  src/app/services/observables/current-house-service.ts
  src/app/services/observables/issue-feed-service.ts
  src/app/views/landlord/house-select/house-select.page.ts
  src/app/views/landlord/issue-detail/issue-detail.page.ts
  src/app/views/landlord/issue-feed/issue-feed.module.ts
  src/app/views/landlord/issue-feed/issue-feed.page.ts
  src/app/views/landlord/new-issue/new-issue.page.ts
  src/app/views/tenant/issue-detail/issue-detail.page.ts
  src/app/views/tenant/issue-feed/issue-feed.page.ts
  src/app/views/tenant/new-issue/new-issue.page.ts
  tslint.json
Labels: enhancement

#66 Navigate back when resolved
  src/app/views/landlord/issue-detail/issue-detail.page.ts
  src/app/views/landlord/issue-feed/issue-feed.module.ts.orig
  src/app/views/landlord/issue-feed/issue-feed.page.ts.orig
  src/app/views/tenant/issue-detail/issue-detail.page.ts
Labels: enhancement
